[package]
name = "cargo-toml-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { path = "macros" }
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
